# Generated by Django 3.1.2 on 2020-10-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernusers',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modernusers',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modernusers',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modernusers',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
