# Generated by Django 3.1.2 on 2020-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernusers',
            name='user_pic',
            field=models.ImageField(default='modern_users/pics/already.png', upload_to='modern_users/pics/'),
        ),
    ]
