# Generated by Django 3.1.2 on 2020-10-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern_users', '0002_modernusers_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modernusers',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
