<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-08 22:14
=======
# Generated by Django 3.1.2 on 2020-10-09 17:03
>>>>>>> 5f2fe9a99f803c351d15c0ff53f196b17c7df453

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('NEWS', 'News'), ('TRAFFIC', 'Traffic'), ('ALERT', 'Alert'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='NEWS', max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_urgent', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
