<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-19 15:44
=======
# Generated by Django 3.1.2 on 2020-10-15 23:36
>>>>>>> 97a8f107eafe08b8172a1f1df71274a779d9362f

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('NEWS', 'News'), ('TRAFFIC', 'Traffic'), ('ALERT', 'Alert'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='NEWS', max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_urgent', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
