# Generated by Django 3.1.2 on 2020-10-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
