# Generated by Django 3.1.2 on 2020-10-12 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
