# Generated by Django 3.1.2 on 2020-10-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='image',
            new_name='notice_pic',
        ),
    ]
